### ISSUE TITLE
Добавление вызова (versus)

### ISSUE THREAD

**Issue by sergio-fry** [HeavyTechRuby/versus#9]
```gherkin
Функция: F02 Добавление соревнования

    Сценарий: F02S01 Я, как участник могу добавить свой versus, чтобы другие пользователи могли принять в нем участие

    Сценарий: F02S02 Я, как участник могу редактировать свой versus
```

**Comment by Keallar** [comment]
Прошу повесить на меня задачу)

**Comment by Keallar** [comment]
@sergio-fry добрый вечер! А предполагается использование devise, чтобы в дальнейшем можно было регистрироваться в том числе на самом ресурсе или сервису хватит использование Omniauth с кастомными проверками авторизации пользователя?

**Comment by sergio-fry** [comment]
Я исходил из того, что проще через сети. Но, кажется, что и через пароль тоже можно - даже хорошо
